#include "src/core/constants.h"
#include "src/dynamics/propulsion.h"

#include "src/io/logger.h"


/**
 * @brief Computes the propulsion forces and moments acting on the aircraft in the body frame.
 *
 * This function calculates the total forces and moments generated by the
 * aircraft's propulsion system, given the control input and aircraft params.
 *
 * @param[in]  X          Pointer to the current state vector.
 * @param[in]  U          Pointer to the control vector, providing throttle settings.
 * @param[in]  acModel   Pointer to the aircraft parameters struct.
 * @param[out] F          Pointer to a `Vector3` where the total propulsion force
 *                        vector in the body frame will be stored.
 * @param[out] M          Pointer to a `Vector3` where the total propulsion moment
 *                        vector in the body frame will be stored.
 */
void computePropulsionForces(const Actuators* actuators, const AircraftModel* acModel, Vector3* F, Vector3* M){

    double Fthrottle1 = actuators->throttle[0] * acModel->mass * g;
    double Fthrottle2 = actuators->throttle[1] * acModel->mass * g;

    Vector3 FengineOne = {Fthrottle1, 0, 0};
    Vector3 FengineTwo = {Fthrottle2, 0, 0};

    *F = vec3_add(FengineOne, FengineTwo);

    Vector3 MomentEngineOne_b = vec3_cross(acModel->r_engineOne2cg, FengineOne);
    Vector3 MomentEngineTwo_b = vec3_cross(acModel->r_engineTwo2cg, FengineTwo);

    *M = vec3_add(MomentEngineOne_b, MomentEngineTwo_b);

    logger.data[LOG_FORCES_F_PROP_X] = F->x;
    logger.data[LOG_FORCES_F_PROP_Y] = F->y;
    logger.data[LOG_FORCES_F_PROP_Z] = F->z;
    logger.data[LOG_MOMENTS_M_PROP_X] = M->x;
    logger.data[LOG_MOMENTS_M_PROP_Y] = M->y;
    logger.data[LOG_MOMENTS_M_PROP_Z] = M->z;
}
